apiVersion: v1
kind: Service
metadata:
  name: test-case-controller-service
spec:
  selector:
    app: test-case-controller
  ports:
    - protocol: TCP
      port: {{ .Values.test_case_controller.ports.serviceport }}
      targetPort: {{ .Values.test_case_controller.ports.containerport }}
