apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-node-service
spec:
  selector:
    app: selenium-chrome-node
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
  clusterIP: None
