apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: log
  labels:
    app: otel-collector
spec:
  ports:
    - name: otlp-grpc
      port: {{ .Values.otel_collector.port }}
      targetPort: {{ .Values.otel_collector.port }}
  selector:
    app: otel-collector
  type: ClusterIP
