apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  ports:
  - port: {{ .Values.selenium_hub.ports.webdriver_port }}
    targetPort: {{ .Values.selenium_hub.ports.webdriver_port }}
    name: port0
  - port: {{ .Values.selenium_hub.ports.secure_webdriver_port }}
    targetPort: {{ .Values.selenium_hub.ports.secure_webdriver_port }}
    name: port1
  - port: {{ .Values.selenium_hub.ports.health_check_port }}
    targetPort: {{ .Values.selenium_hub.ports.health_check_port }}
    name: port2
  selector:
    app: selenium-hub
  type: NodePort
  sessionAffinity: None
