apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  replicas: {{ .Values.selenium_hub.replica_count }}
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: {{ .Values.selenium_hub.image }}
        ports:
          - containerPort: {{ .Values.selenium_hub.ports.webdriver_port }}
          - containerPort: {{ .Values.selenium_hub.ports.secure_webdriver_port }}
          - containerPort: {{ .Values.selenium_hub.ports.health_check_port }}
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: {{ .Values.selenium_hub.ports.webdriver_port }}
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /wd/hub/status
            port: {{ .Values.selenium_hub.ports.webdriver_port }}
          initialDelaySeconds: 30
          timeoutSeconds: 5
